import type { MediaIndex, Post } from './types.ts'
import { pickMedia, pickMediaEntry } from './media.ts'
import { MEDIA_MAX_AGE } from './cache.ts'

/**
 * SERVE THE VIDEO BYTES OURSELVES INSTEAD OF 302-ING TO META'S CDN.
 *
 * MEASURED 2026-07-25, and the measurement is the whole reason this module exists. Instagram reel
 * DbOwAfWp0YT (38,774,320 bytes) and DZc6RL8sHtz (2,471,034 bytes) both 302 to
 * scontent-*.cdninstagram.com. On a PLAIN GET the big one's 200 carries NO `accept-ranges: bytes`;
 * the small one's DOES (3/3 each). Both honour Range anyway (`bytes=0-99` -> 206 + content-range).
 * So the client behind our redirect is told it may range-fetch the file that fits and NOT the one
 * that does not, and must pull 38MB whole inside its own timeout — which is exactly the pair of
 * outcomes the human measured (the 14s reel renders in Discord, the 119s reel draws no card at
 * all). A 302 cannot add a header to someone else's response. The competing fixer instagram7.com
 * serves the byte-identical 38,774,320-byte file from its OWN domain and always emits
 * accept-ranges on its 200 (`x-instagram7-video-stream: direct`, i.e. a streaming pass-through,
 * not a stored copy) — and it works in Discord. Hence: we stream, and WE advertise.
 *
 * NOTHING TO REMUX. Instagram hands us ONE complete progressive mp4 (`ftyp` then `moov` at offset
 * 0x20 on both reels — faststart, so ~128KB of range answers a metadata probe). That is the
 * difference from `remux` (worker.ts's serveMuxed): no container, no R2, no cold path.
 *
 * WHY A SEPARATE MODULE, not a few lines in worker.ts: test/pipeline.test.mjs's probe enforcer
 * ("the probe enforcer is HAZARD-scoped, not NAME-scoped") strips comments from src/worker.ts and
 * asserts it contains ZERO bare `fetch(` calls — the dispatcher reaches the network only through
 * injected deps or a platform fetcher. That invariant is worth keeping, so the one new egress site
 * lives here and worker.ts calls it by import.
 */

/**
 * Meta's two CDN domains, and the allowlist is the SSRF boundary. The url we stream comes out of a
 * cached Post — our own extraction for the ref in the path — but a cache record is not the
 * normalizer's output by the time it reaches here (cache.ts says so at length), so the host is
 * range-checked before any I/O rather than trusted.
 */
const PROXY_HOSTS = ['cdninstagram.com', 'fbcdn.net']

/**
 * TWITCH'S LIVE CLIP FLEET. A PREDICATE rather than a row in the suffix list above, and — this is the
 * part that matters — a DELIBERATELY NARROW one that doubles as a tombstone detector.
 *
 * A 1015-clip census (2026-07-27) found `sourceURL` on exactly TWO hosts:
 *
 *     d1ndex63qxojbr.cloudfront.net              1003 clips   LIVE   (signed -> 206 + real mp4)
 *     production.assets.clips.twitchcdn.net        12 clips   DEAD   (signed -> 403 AccessDenied)
 *
 * THE SECOND HOST IS A TOMBSTONE, AND IT IS INVISIBLE IN THE METADATA. Those twelve clips return a
 * complete, healthy-looking payload — title, broadcaster, game, view count, `isPublished: true`, and
 * a playback token whose `authorization.forbidden` is FALSE — and then serve no bytes at all
 * (unsigned 404, signed 403 with an S3 AccessDenied body); their thumbnails 302 to Twitch's own
 * `404_preview.jpg`. A blind random sample of 120 clips correlated host to liveness at 100%. So the
 * HOST is the only available signal, and excluding it here is what stops a card rendering a player
 * over dead bytes — the metadata-alive/media-dead failure that is far worse than an honest miss.
 *
 * `cloudfront.net` IS NOT ALLOWLISTED AS A SUFFIX. That would admit ANY CloudFront distribution, i.e.
 * a large fraction of the CDN-hosted internet, and an allowlist that accepts an attacker-chosen
 * origin is not an allowlist. The generated label is matched in its generated SHAPE — one
 * lowercase-alnum label directly under cloudfront.net — which cannot match a deeper
 * attacker-controlled name like `evil.example.cloudfront.net`.
 *
 * NOT PINNED TO `d1ndex63qxojbr` EITHER: that label is autogenerated and stable-but-not-a-contract,
 * so pinning it would break every clip the day Twitch reprovisions. The shape is the compromise, and
 * it fails CLOSED — an unrecognised host degrades the clip to a still or a text card.
 *
 * THUMBNAILS AND AVATARS ARE NOT HERE, deliberately: they live on `static-cdn.jtvnw.net` (314/314 in
 * the census) and images are 302'd rather than proxied, so they never cross this boundary.
 *
 * EXPORTED so platforms/twitch/normalize.ts asks the SAME question when it builds the signed url —
 * the same one-spelling rule allowedHost's docstring states, for the same reason.
 */
export function twitchMediaHost(url: string): boolean {
  try {
    const u = new URL(url)
    if (u.protocol !== 'https:') return false
    return /^[a-z0-9]{8,20}\.cloudfront\.net$/.test(u.hostname.toLowerCase())
  } catch {
    return false
  }
}

/**
 * "https, on a host we have measured." ONE spelling, because it is now asked THREE times — before
 * the fetch (proxyableVideoUrl, the pure decision), again on the url the fetch actually LANDED on
 * (serveDirectVideo), and now on a url that arrives from a DIFFERENT upstream surface entirely
 * (instagram/normalize.ts's withRecoveredVideo, which reads the v1 user-feed rather than the embed).
 * Two copies of an SSRF boundary is two places for one of them to drift, and the drift is the
 * vulnerability — so the third caller IMPORTS this rather than spelling it again.
 *
 * EXPORTED FOR THAT REASON ALONE. It is pure (no I/O, total over junk), so a normalizer may call it
 * without becoming impure; that is what makes reuse across the layer boundary sound rather than a
 * shortcut.
 */
export function allowedHost(url: string): boolean {
  try {
    const u = new URL(url)
    if (u.protocol !== 'https:') return false
    const host = u.hostname.toLowerCase()
    return PROXY_HOSTS.some(h => host === h || host.endsWith(`.${h}`))
  } catch {
    return false
  }
}

/**
 * THE WHOLE BYTE-PROXY BOUNDARY: Meta's CDNs (allowedHost) plus Twitch's clip fleet. Separate from
 * allowedHost because that one has a SECOND consumer with a narrower question — instagram's
 * withRecoveredVideo asks "is this a Meta CDN url I may put in a Post", and widening it there would
 * silently let a Twitch host through a check that exists for Instagram's recovery path.
 */
export function proxyHost(url: string): boolean {
  return allowedHost(url) || twitchMediaHost(url)
}

/**
 * THE URL WE SERVE OURSELVES — pure, so the SSRF-relevant half of the decision is decided before
 * any I/O and is testable with no network. Null means "keep today's 302", which is the honest miss
 * direction: an unmeasured host degrades to shipped behaviour, never to a server-side request we
 * have no evidence for. That is also what keeps TikTok (tiktokcdn) and Twitter (video.twimg.com)
 * on the 302 they were measured good on.
 */
export function proxyableVideoUrl(post: Post, index: MediaIndex): string | null {
  // 'avatar' and {poster:N} are IMAGES and keep the 302 — see the media route's comment for why
  // images are deliberately not proxied.
  if (typeof index !== 'number') return null
  /**
   * INSTAGRAM ONLY — SCOPED TO THE PLATFORM THAT WAS ACTUALLY MEASURED (2026-07-25).
   *
   * THREADS IS THE REASON THIS LINE EXISTS. Threads video is Instagram's backend and its urls are on
   * scontent*.cdninstagram.com, so a host-only allowlist captured it too — and that would have been a
   * REGRESSION on a platform that works today. platforms/threads/normalize.ts's mediaFromDict docstring
   * records the measurement: Meta blocks Cloudflare's DATACENTER egress for Threads media ("our container
   * can't fetch it … that fetch is a datacenter IP; Discord's proxy is not"), which is precisely why
   * Threads video is served by a 302 to Discord's own proxy and plays. The Worker's egress is a
   * datacenter IP too, so serving those bytes ourselves would most likely get a non-video response, fail
   * the content assertion, and answer the url og:video points at with 503 — killing the player on EVERY
   * Threads video post. Revisit ONLY with a real measurement of a Worker-egress fetch of a Threads
   * scontent url; until then the measured-good 302 stands.
   *
   * Every other platform is out by construction rather than by this line — Twitter/TikTok on their own
   * CDNs (allowedHost says no), Facebook/YouTube/Reddit/Bluesky because their video carries `remux`
   * (refused below) — but Threads was in, and only the ref can tell it apart from Instagram.
   *
   * Read defensively off `post.ref`: this arrives from the cache, not the normalizer.
   */
  /**
   * TWITCH JOINS INSTAGRAM HERE, and for a DIFFERENT measured reason worth stating separately.
   *
   * Instagram is proxied because a 302 cannot add `accept-ranges` to someone else's response (see the
   * module head). Twitch's CloudFront already advertises accept-ranges and serves a faststart mp4
   * (`moov` immediately after `ftyp`), so that argument does not apply. What DOES apply is the
   * CONTENT TYPE: measured 2026-07-27 on all four renditions, the clip fleet answers
   * `content-type: binary/octet-stream` for a file whose first bytes are literally
   * `ftypisom…iso2avc1mp41`. A 302 hands Discord that label and nothing of ours can correct it.
   *
   * A SECOND, INDEPENDENT REASON: the rendition urls live under `/nauth/` and are 401 without the
   * signed token, so the bytes are fetched by whoever follows the url. Doing it ourselves keeps the
   * fetch on the same egress that MINTED the token. The token's signed document carries no client
   * address (`{authorization, clip_uri, clip_slug, device_id, expires, user_id, version}` — measured),
   * so it should not be address-bound; proxying means we do not have to rely on that being true.
   */
  const p = (post?.ref as { p?: string } | undefined)?.p
  if (p !== 'ig' && p !== 'tw') return null
  const m = pickMediaEntry(post, index)
  // `remux` is the container's job (serveMuxed); its `url` is a manifest/page placeholder and must
  // never be streamed raw. Mutually exclusive with that branch by construction, twice over: the
  // remux branch returns before this is reached, and this refuses a remux entry anyway.
  if (!m || m.kind !== 'video' || m.remux) return null
  // pickMedia, not m.url: it is the DEFENSIVE read (a number, a hole, an empty string in a
  // corrupted cache record all become null) that this route already trusts for the 302.
  const url = pickMedia(post, index)
  if (!url) return null
  return proxyHost(url) ? url : null
}

/** The single-range form r2Range already speaks. Multi-range is not forwarded — see below. */
const RANGE = /^bytes=\d*-\d*$/

/**
 * Stream the CDN bytes through, honouring Range. Returns null on ANY no, so the "503 + no-store"
 * convention keeps exactly ONE spelling, in worker.ts's shared notReady().
 */
export async function serveDirectVideo(req: Request, url: string): Promise<Response | null> {
  const head = req.method === 'HEAD'
  const inbound = req.headers.get('range')
  // ONLY a single `bytes=a-b`. A multi-range would come back multipart/byteranges, which the
  // content assertion below then refuses — so forwarding nothing and answering 200 is the
  // degradation, not a 503. Same single-range rule r2Range enforces on the mux path.
  const range = inbound && RANGE.test(inbound) ? inbound : null
  let up: Response
  try {
    up = await fetch(url, {
      method: head ? 'HEAD' : 'GET',
      headers: range ? { range } : {},
      redirect: 'follow',
    })
  } catch {
    return null
  }
  /**
   * THE ALLOWLIST AGAIN, ON THE URL THE FETCH ACTUALLY LANDED ON — and it is checked FIRST, before
   * the status and before the content type, so an off-allowlist response is never even inspected.
   *
   * `redirect: 'follow'` means the pre-fetch check above constrains only the FIRST hop: an
   * allowlisted Meta host that 302s elsewhere would otherwise have us making a server-side request to
   * an unvetted origin and streaming its bytes out under OUR domain. That is the end-to-end claim the
   * pure-decision test could not see, because it only exercises the pre-fetch half.
   *
   * FOLLOW IS KEPT rather than swapped for the `redirect: 'manual'` that tiktok/fetch.ts and
   * reddit/fetch.ts use deliberately: Meta really does shard-redirect between scontent hosts, and
   * hand-walking those hops would buy only what is described next.
   *
   * WHAT THIS CHECK DOES AND DOES NOT COVER, stated precisely because an earlier version of this
   * comment overclaimed it. Checked: the url we ASK for (pre-fetch) and the url the bytes finally
   * COME FROM (`up.url`). NOT checked: any INTERMEDIATE hop — with `follow`, workerd performs a real
   * server-side request to each one and only the final url is observable to us. So a redirect chain
   * can touch an off-allowlist host in the middle; what it cannot do is deliver that host's BYTES,
   * because the final origin is re-checked before the body is read and a miss cancels it. The
   * residual exposure is therefore a blind GET (no response of ours carries its content, its status
   * or its timing), not an exfiltration channel or an open proxy. Swapping to `manual` would close
   * even that, at the cost of hand-walking Meta's shard hops; if that trade ever looks worth making,
   * this is the paragraph to revisit.
   *
   * `up.url &&`: the runtime always populates Response.url for a real fetch, but a hand-built
   * `new Response(...)` (every stub under `node --test`) reports ''. An absent final url means the
   * runtime told us nothing about redirects, and the url we ASKED for was already allowlisted — so
   * that degrades to the pre-fetch decision rather than refusing every stubbed response.
   */
  if (up.url && !proxyHost(up.url)) { void up.body?.cancel(); return null }
  if (up.status !== 200 && up.status !== 206) { void up.body?.cancel(); return null }
  /**
   * ASSERT ON CONTENT, NEVER ON STATUS — the standing rule on every social platform here, and it is
   * load-bearing at THIS line specifically: Meta answers a block with HTTP 200 and text/html, and
   * streaming that body under the url og:video points at is the poisoned-content-type family of
   * defect serveMuxed's 503 exists to prevent. A 416 folds in here too: unsatisfiable is a
   * pathological client, and 503 no-store is a fine answer for it. Do not relax this to accept
   * application/octet-stream without a measurement — both reels answered `video/mp4` on 2026-07-25.
   */
  const ct = up.headers.get('content-type') ?? ''
  /**
   * THE ASSERTION IS PER-ORIGIN, and the exception is scoped to the ONE host it was measured on
   * rather than to a content-type string. The rule above still stands everywhere else: Meta answers a
   * block with HTTP 200 and text/html, and `application/octet-stream` is exactly what a generic
   * blocked-or-error body looks like, so accepting that label GLOBALLY would re-open the
   * poisoned-content-type hole this line exists to close.
   *
   * TWITCH IS THE EXCEPTION BECAUSE ITS CORRECT ANSWER IS THE WRONG LABEL. Measured 2026-07-27 on
   * 1080/720/480/360 of a healthy public clip: HTTP 206, `content-type: binary/octet-stream`,
   * `accept-ranges: bytes`, and a body beginning `00000020 66747970 69736f6d` —
   * `ftypisom…iso2avc1mp41`, an ISO-BMFF mp4, with `moov` at offset 0x28. The bytes are a real mp4;
   * only the header is wrong. Refusing them would mean refusing every Twitch clip, and relaying the
   * label would hand Discord a video it will not play.
   *
   * NOTE the spelling is `binary/octet-stream`, NOT `application/octet-stream` — that is what
   * CloudFront actually sent, and matching the exact measured string keeps this from quietly widening
   * into the generic label if Twitch ever changes it. It also means such a change fails CLOSED (the
   * clip stops proxying and degrades) rather than silently accepting a new, unmeasured body class.
   */
  const twitchOctet = twitchMediaHost(up.url || url) && /^binary\/octet-stream$/i.test(ct.split(';')[0].trim())
  if (!/^video\//i.test(ct) && !twitchOctet) { void up.body?.cancel(); return null }
  // RELAYED, NOT PINNED to video/mp4. We asserted the CLASS; relabelling a hypothetical video/webm
  // as mp4 would be us authoring the mislabel this route exists to avoid.
  //
  // The Twitch arm is the ONE place a label is rewritten, and it is a CORRECTION rather than an
  // invention: the container was read off the bytes (see above), and `video/mp4` is what those bytes
  // are. Emitting `binary/octet-stream` here would make the whole proxy pointless — that label is the
  // entire reason these bytes are streamed instead of 302'd.
  const h = new Headers({
    'content-type': twitchOctet ? 'video/mp4' : ct,
    // ALWAYS, even on a 200 the CDN sent without it. This header is the fix (see the module head).
    'accept-ranges': 'bytes',
    // OURS, never the CDN's `max-age=1209600`: our /_media/ url is the stable one Discord caches,
    // the CDN url behind it is re-minted from a fresh Post on every miss, and 300 is what the 302
    // has always emitted here (and what instagram7 emits — measured 2026-07-25).
    'cache-control': `public, max-age=${MEDIA_MAX_AGE}`,
  })
  const cr = up.headers.get('content-range')
  if (cr) h.set('content-range', cr)
  const cl = up.headers.get('content-length')
  // Only when upstream did NOT encode the body: the runtime decompresses, so a relayed length would
  // describe bytes we are not sending. mp4 is never encoded; this is the belt.
  if (cl && !up.headers.get('content-encoding')) h.set('content-length', cl)
  if (head) { void up.body?.cancel(); return new Response(null, { status: up.status, headers: h }) }
  return new Response(up.body, { status: up.status, headers: h })
}
